### ISSUE TITLE
Добавить игру в игре

### ISSUE THREAD

**Issue by pauldyatlov** [pauldyatlov/beardythedigger#11]
- [x] В главном меню при нажатии пробела открывается секретный режим, в котором копатель может прыгать, а поле превращается в поле с препятствиями.

- [x] При столкновении с препятствием идет проигрыш в мини-игре, копатель умирает и потом вновь появляется в главном меню, при этом мини-игра завершается, и нужно снова нажать пробел, чтобы продолжить.

- [x] Чтобы счетчик очков увеличивался за каждые примерно 0.2 секунды

- [x] Хранить Highscore между сессиями и показывать его во время мини игры, если он больше 0

- [x] Постепенно увеличивать Time.timeScale

- [x] Ты проиграл в мини игре, умер об стену, проигралась анимация смерти, и копатель автоматически встает обратно

~~- [ ] При перепрыгивании препятствия добавляется 1 к счетчику преодоленных препятствий (справа сверху). Этот показатель нигде не сохраняется, а лишь отображается при текущей мини-игре.~~ - не делаем

**Comment by antonkanin** [comment]
Надо сделать

1) Чтобы Level2 И остальные, еще не сделанные, добавлялись в этот список после первого прыжка
2) Починить сам прыжок
3) Смерть и жизнь после смерти
4) Счетчик успешных прыжков

**Comment by antonkanin** [comment]
Новые требования: Ты проиграл в мини игре, умер об стену, проигралась анимация смерти, и копатель автоматически встает обратно

**Comment by antonkanin** [comment]
Сделано, можно наливать.
