### ISSUE TITLE
DeathScreen не показывается после смерти (View падает с эксепшеном)

### ISSUE THREAD

**Issue by pauldyatlov** [pauldyatlov/beardythedigger#4]
MissingReferenceException: The object of type 'Animator' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Animator.SetBool (System.String name, System.Boolean value) (at C:/buildslave/unity/build/Modules/Animation/ScriptBindings/Animator.bindings.cs:343)
View.SetBoolAnimation (System.String animationName, System.Boolean value) (at Assets/Scripts/Components/View/View.cs:22)
PlayerUnit.Stop () (at Assets/Scripts/Components/Target/Unit/Player/PlayerUnit.cs:101)
PlayerCharacter.Stop () (at Assets/Scripts/Components/Character/Player/PlayerCharacter.cs:133)
PlayerCharacter.SetMoveState (System.Boolean state) (at Assets/Scripts/Components/Character/Player/PlayerCharacter.cs:171)
ViewManager.AddViewController (UIViewController viewController, System.Boolean freezeMove) (at Assets/Scripts/UI/ViewManager.cs:17)
GameController.DeathFinishedHandler () (at Assets/Scripts/Controllers/GameControllers/GameController.cs:280)
PlayerCharacter.DeathFinishedHandler () (at Assets/Scripts/Components/Character/Player/PlayerCharacter.cs:195)
PlayerUnit.<Death>b__52_0 () (at Assets/Scripts/Components/Target/Unit/Player/PlayerUnit.cs:198)
Scorch.Update () (at Assets/Scripts/Components/View/Scorch.cs:48)

**Comment by antonkanin** [comment]
Fixed
